### PR TITLE
[Tree] Add a solution to Recover Binary Search Tree

### PR DESCRIPTION
**Pull request by demonkoo**
Please have a look at my accepted solution for 99. Recover Binary Search Tree

### CODE REVIEW

**Comment by soapyigu** [comment]
Hi,

Could you please edit the README file as well?

1. Change the solution number
2. Add the solution to Tree category
3. Add the solution to All solution list

Thank you,
Yi

**Comment by demonkoo** [comment]
Sorry, but what's the meaning of "change the solution number"?

**Comment by soapyigu** [comment]
You can find "Progress" session in README, and there marks the numbers of questions we solved. Now it is 178.

**Comment by demonkoo** [comment]
Understand, thanks!

**Comment by demonkoo** [comment]
I have just modified the README.md, please have a look.

**Pull request merged**
